extends SceneTree

const PackKeepState = preload("res://src/core/keep_state.gd")

var failures: Array[String] = []

func _init() -> void:
	_test_castellan_and_basic_roster()
	_test_two_floor_placement_and_overlap()
	_test_hold_against_gate_assault()
	_test_sapper_targeting_and_repair()
	_test_climber_targets_upper_floor()
	_test_lockdown_changes_room_damage()
	_test_partial_breach_is_recoverable()
	_test_repair_interval_and_assignments()
	_test_assignment_rules_and_action_budget()
	_test_deterministic_battle_report()
	_test_save_round_trip()
	if failures.is_empty():
		print("PASS: Pack the Keep battle-state tests")
		quit(0)
	else:
		for failure in failures:
			push_error(failure)
		quit(1)

func _expect(condition: bool, message: String) -> void:
	if not condition:
		failures.append(message)

func _test_castellan_and_basic_roster() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	var commander: Dictionary = keep.select_commander("castellan")
	_expect(bool(commander.get("ok", false)), "Castellan should be selectable")
	_expect(keep.commander_id == "castellan", "Castellan should be stored as the active commander")
	_expect(PackKeepState.PIECES.has("pike_squad"), "Pike Squad should be in the basic roster")
	_expect(PackKeepState.PIECES.has("repair_station"), "Repair Station should be in the basic roster")
	_expect(PackKeepState.PIECES.has("fire_team"), "Fire Team should be in the basic roster")
	_expect(PackKeepState.PIECES.has("scout_post"), "Scout Post should be in the basic roster")
	_expect(PackKeepState.ENEMIES.size() == 3, "the first slice should have three basic enemy types")
	_expect(keep.open_pack("pike_line").get("ok", false), "Pike Line pack should open")
	_expect(not bool(keep.open_pack("pike_line").get("ok", false)), "the same pack should not open twice")

func _test_two_floor_placement_and_overlap() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	var ground_piece: Dictionary = keep.place_piece("pike_squad", Vector2i(0, 3), "ground")
	_expect(bool(ground_piece.get("ok", false)), "Pike Squad should fit on the ground floor")
	var ground_overlap: Dictionary = keep.place_piece("fire_team", Vector2i(1, 3), "ground")
	_expect(not bool(ground_overlap.get("ok", false)), "overlap on one floor should be rejected")
	var upper_same_space: Dictionary = keep.place_piece("scout_post", Vector2i(0, 3), "upper")
	_expect(bool(upper_same_space.get("ok", false)), "the upper floor may use the same footprint")
	_expect(not keep.piece_fits("fire_team", Vector2i(11, 7), "ground"), "a piece beyond the keep grid should not fit")

func _test_hold_against_gate_assault() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	keep.place_piece("pike_squad", Vector2i(0, 3), "ground")
	keep.place_piece("fire_team", Vector2i(4, 3), "ground")
	var started: Dictionary = keep.start_wave("gate_assault")
	_expect(bool(started.get("ok", false)), "gate assault should start with a placed defense")
	_expect(String(started.get("forecast", {}).get("likely_target", "")) == "gate", "gate assault should forecast the Gate")
	var result: Dictionary = keep.advance_wave(6.0)
	_expect(bool(result.get("resolved", false)), "six seconds should resolve the basic wave")
	_expect(String(result.get("outcome", "")) == "held", "Pike Line should hold the basic Raider wave")
	_expect(keep.room_condition("gate") == 100, "a successful Pike Line should prevent Gate damage")
	_expect(keep.materials > 43, "holding a wave should award recovery materials")

func _test_sapper_targeting_and_repair() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	keep.place_piece("pike_squad", Vector2i(0, 3), "ground")
	keep.place_piece("repair_station", Vector2i(4, 6), "ground")
	keep.place_piece("scout_post", Vector2i(8, 1), "upper")
	var started: Dictionary = keep.start_wave("distributed_sabotage")
	_expect(bool(started.get("ok", false)), "distributed sabotage should start")
	var result: Dictionary = keep.advance_wave(6.0)
	_expect(bool(result.get("resolved", false)), "distributed sabotage should resolve in the slice")
	_expect(keep.room_condition("workshop") < 100 or keep.room_condition("supply_room") < 100 or keep.room_condition("armory") < 100, "Sapper should damage a support target")
	_expect(String(result.get("timeline", []).filter(func(line: String) -> bool: return line.contains("Sapper reached")).front()).contains("Sapper reached"), "battle report should explain Sapper targeting")
	var repaired: Dictionary = keep.repair_room("workshop")
	_expect(bool(repaired.get("ok", false)) or keep.room_condition("workshop") == 100, "a damaged support room should have a repair path")

func _test_climber_targets_upper_floor() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	keep.place_piece("scout_post", Vector2i(8, 1), "upper")
	var started: Dictionary = keep.start_wave("feint_and_flank")
	_expect(bool(started.get("ok", false)), "feint and flank should start")
	var result: Dictionary = keep.advance_wave(6.0)
	_expect(bool(result.get("resolved", false)), "climber wave should resolve")
	_expect(keep.room_condition("north_tower") < 100 or keep.room_condition("old_chapel") < 100, "Climber should target an upper-floor room")

func _test_lockdown_changes_room_damage() -> void:
	var normal: PackKeepState = PackKeepState.new(3307)
	var locked: PackKeepState = PackKeepState.new(3307)
	normal.place_piece("scout_post", Vector2i(0, 0), "upper")
	locked.place_piece("scout_post", Vector2i(0, 0), "upper")
	normal.start_wave("gate_assault")
	locked.start_wave("gate_assault")
	locked.use_commander_ability()
	normal.advance_wave(2.0)
	locked.advance_wave(2.0)
	_expect(locked.room_condition("gate") > normal.room_condition("gate"), "Lockdown should reduce the next contact damage")
	_expect(locked.command_points == 2, "Lockdown should consume one command point")
	_expect(not bool(locked.use_commander_ability().get("ok", false)), "Lockdown should be limited to once per wave")

func _test_partial_breach_is_recoverable() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	keep.place_piece("scout_post", Vector2i(0, 0), "upper")
	keep.start_wave("gate_assault")
	var result: Dictionary = keep.advance_wave(6.0)
	_expect(String(result.get("outcome", "")) == "partial_breach", "an unsupported Gate should create a partial breach rather than a silent win")
	_expect(not keep.wave_active, "a resolved partial breach should leave the wave inactive")
	_expect(keep.room_state("gate") == "breached", "the report should identify the breached Gate")
	var repair: Dictionary = keep.repair_room("gate")
	_expect(bool(repair.get("ok", false)), "a partial breach should expose a repair path")

func _test_repair_interval_and_assignments() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	keep.place_piece("scout_post", Vector2i(8, 1), "upper")
	keep.start_wave("gate_assault")
	var result: Dictionary = keep.advance_wave(6.0)
	_expect(String(result.get("outcome", "")) == "partial_breach", "unsupported Gate should open a recoverable interval")
	_expect(keep.repair_interval_active, "held or partial-breach outcomes should open the repair interval")
	_expect(keep.repair_actions_remaining == 2, "Greywatch interval should begin with two actions")
	var repaired: Dictionary = keep.repair_room("gate")
	_expect(bool(repaired.get("ok", false)), "the first interval action should repair a named room")
	_expect(keep.room_condition("gate") == 30, "repair should restore a breached room to 30 condition")
	var assignment: Dictionary = keep.assign_piece_to_room("scout_post_0", "north_tower")
	_expect(bool(assignment.get("ok", false)), "the second interval action should assign Scout Post to North Tower")
	_expect(keep.assigned_rooms.get("north_tower", "") == "scout_post_0", "assignment should be stored by room")
	_expect(keep.pieces["scout_post_0"].get("assignment", "") == "north_tower", "assignment should be stored on the piece")
	_expect(keep.repair_actions_remaining == 0, "two repair interval actions should be consumed")
	_expect(not bool(keep.start_wave("gate_assault").get("ok", false)), "the next wave should wait for interval closure")
	var finished: Dictionary = keep.finish_repair_interval()
	_expect(bool(finished.get("ok", false)), "the repair interval should close explicitly")
	_expect(not keep.repair_interval_active, "closed interval should no longer block a wave")
	_expect(bool(keep.start_wave("gate_assault").get("ok", false)), "a new wave should start after interval closure")

func _test_assignment_rules_and_action_budget() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	keep.place_piece("pike_squad", Vector2i(0, 3), "ground")
	keep.place_piece("repair_station", Vector2i(4, 6), "ground")
	keep.start_wave("gate_assault")
	keep.advance_wave(6.0)
	var pike_assignment: Dictionary = keep.assign_piece_to_room("pike_squad_0", "workshop")
	_expect(not bool(pike_assignment.get("ok", false)), "Pike Squad should reject an invalid room-role assignment")
	var valid_pike: Dictionary = keep.assign_piece_to_room("pike_squad_0", "gate")
	_expect(bool(valid_pike.get("ok", false)), "Pike Squad should assign to the Gate")
	var valid_repair: Dictionary = keep.assign_piece_to_room("repair_station_1", "workshop")
	_expect(bool(valid_repair.get("ok", false)), "Repair Station should assign to the Workshop")
	_expect(not bool(keep.assign_piece_to_room("pike_squad_0", "gate").get("ok", false)), "an already assigned piece should not be assigned twice")
	_expect(not bool(keep.repair_room("gate").get("ok", false)), "no third interval action should be available")
	_expect(bool(keep.finish_repair_interval().get("ok", false)), "interval should close after assignment actions")

func _test_deterministic_battle_report() -> void:
	var first: PackKeepState = PackKeepState.new(17)
	var second: PackKeepState = PackKeepState.new(17)
	for keep in [first, second]:
		keep.place_piece("pike_squad", Vector2i(0, 3), "ground")
		keep.place_piece("repair_station", Vector2i(4, 6), "ground")
		keep.place_piece("scout_post", Vector2i(8, 1), "upper")
		keep.start_wave("distributed_sabotage")
	first.advance_wave(6.0)
	second.advance_wave(6.0)
	_expect(first.last_outcome == second.last_outcome, "same seed and layout should produce the same outcome")
	_expect(first.rooms == second.rooms, "same seed and layout should produce the same room state")
	_expect(first.battle_report == second.battle_report, "same seed and layout should produce the same causal report")

func _test_save_round_trip() -> void:
	var keep: PackKeepState = PackKeepState.new(17)
	keep.place_piece("pike_squad", Vector2i(0, 3), "ground")
	keep.place_piece("scout_post", Vector2i(8, 1), "upper")
	keep.start_wave("feint_and_flank")
	keep.advance_wave(1.0)
	var restored: PackKeepState = PackKeepState.new(0)
	restored.load_serialized(keep.serialize())
	_expect(restored.seed == 17, "save should preserve seed")
	_expect(restored.commander_id == "castellan", "save should preserve commander")
	_expect(restored.pieces.size() == 2, "save should preserve pieces")
	_expect(restored.rooms == keep.rooms, "save should preserve room condition")
	_expect(restored.enemies == keep.enemies, "save should preserve active enemies")
	_expect(restored.wave_active == keep.wave_active, "save should preserve wave state")
