extends SceneTree

const PackKeepState = preload("res://src/core/keep_state.gd")

var failures: Array[String] = []

func _init() -> void:
	_test_castellan_and_basic_roster()
	_test_unit_availability_and_metrics()
	_test_two_floor_placement_and_overlap()
	_test_hold_against_gate_assault()
	_test_sapper_targeting_and_repair()
	_test_climber_targets_upper_floor()
	_test_lockdown_changes_room_damage()
	_test_partial_breach_is_recoverable()
	_test_repair_interval_and_assignments()
	_test_assignment_rules_and_action_budget()
	_test_recovery_action_previews()
	_test_causal_scenario_reports()
	_test_layout_summary_and_commander_comparison()
	_test_deterministic_battle_report()
	_test_save_round_trip()
	_test_p0_pack_preview_and_reserve()
	_test_p0_placement_preview_and_inspection()
	_test_p0_save_rejection_and_reset()
	_test_p1_warden_and_rally()
	_test_p1_siege_beast_area_pressure()
	_test_p1_scenario_escalation()
	_test_p1_seeded_variation()
	if failures.is_empty():
		print("PASS: Pack the Keep battle-state tests")
		quit(0)
	else:
		for failure in failures:
			push_error(failure)
		quit(1)

func _expect(condition: bool, message: String) -> void:
	if not condition:
		failures.append(message)

func _test_castellan_and_basic_roster() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	var commander: Dictionary = keep.select_commander("castellan")
	_expect(bool(commander.get("ok", false)), "Castellan should be selectable")
	_expect(keep.commander_id == "castellan", "Castellan should be stored as the active commander")
	_expect(not keep.piece_definition("pike_squad").is_empty(), "Pike Squad should be in the basic roster")
	_expect(not keep.piece_definition("repair_station").is_empty(), "Repair Station should be in the basic roster")
	_expect(not keep.piece_definition("fire_team").is_empty(), "Fire Team should be in the basic roster")
	_expect(not keep.piece_definition("scout_post").is_empty(), "Scout Post should be in the basic roster")
	_expect(keep.enemy_ids().size() == 7, "P11 should expose the baseline enemies plus Siege Beast, Shield Guard, Ash Slinger, and Shieldbreaker")
	_expect(keep.open_pack("pike_line").get("ok", false), "Pike Line pack should open")
	_expect(not bool(keep.open_pack("pike_line").get("ok", false)), "the same pack should not open twice")

func _test_unit_availability_and_metrics() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	var unavailable: Dictionary = keep.place_piece("repair_station", Vector2i(4, 6), "ground")
	_expect(not bool(unavailable.get("ok", false)), "non-starter units should require an opened pack")
	_expect(keep.available_pieces.has("pike_squad"), "Pike Squad should be available as a starter unit")
	_expect(keep.open_pack("field_engineers").get("ok", false), "Field Engineers should unlock its units")
	_expect(keep.open_pack("scouts").get("ok", false), "Scouts should unlock its units")
	_expect(not bool(keep.open_pack("firekeepers").get("ok", false)), "the first Preparation should cap pack openings at two")
	keep.place_piece("pike_squad", Vector2i(0, 3), "ground")
	var station: Dictionary = keep.place_piece("repair_station", Vector2i(4, 6), "ground")
	_expect(bool(station.get("ok", false)), "an unlocked unit should be placeable")
	var started: Dictionary = keep.start_wave("gate_assault")
	_expect(bool(started.get("ok", false)), "availability should still allow the first battle")
	var result: Dictionary = keep.advance_wave(6.0)
	_expect(bool(result.get("resolved", false)), "metric test wave should resolve")
	_expect(int(keep.combat_metrics.get("battle_steps", 0)) > 0, "combat metrics should count battle steps")
	_expect(int(keep.combat_metrics.get("unit_attacks", 0)) > 0, "combat metrics should count unit attacks")
	_expect(int(keep.combat_metrics.get("damage_dealt", 0)) > 0, "combat metrics should count damage dealt")
	_expect(int(keep.combat_metrics.get("defeated_enemies", 0)) == 2, "combat metrics should count both defeated Raiders")
	_expect(int(keep.pieces["pike_squad_0"].get("max_health", 0)) == 14, "unit instances should store max health")
	_expect(int(keep.pieces["pike_squad_0"].get("health", 0)) == 14, "healthy units should retain full health")

func _test_two_floor_placement_and_overlap() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	var ground_piece: Dictionary = keep.place_piece("pike_squad", Vector2i(0, 3), "ground")
	_expect(bool(ground_piece.get("ok", false)), "Pike Squad should fit on the ground floor")
	var ground_overlap: Dictionary = keep.place_piece("fire_team", Vector2i(1, 3), "ground")
	_expect(not bool(ground_overlap.get("ok", false)), "overlap on one floor should be rejected")
	keep.open_pack("scouts")
	var upper_same_space: Dictionary = keep.place_piece("scout_post", Vector2i(0, 3), "upper")
	_expect(bool(upper_same_space.get("ok", false)), "the upper floor may use the same footprint")
	_expect(not keep.piece_fits("fire_team", Vector2i(11, 7), "ground"), "a piece beyond the keep grid should not fit")

func _test_hold_against_gate_assault() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	keep.place_piece("pike_squad", Vector2i(0, 3), "ground")
	keep.open_pack("firekeepers")
	keep.place_piece("fire_team", Vector2i(4, 3), "ground")
	var started: Dictionary = keep.start_wave("gate_assault")
	_expect(bool(started.get("ok", false)), "gate assault should start with a placed defense")
	_expect(String(started.get("forecast", {}).get("likely_target", "")) == "gate", "gate assault should forecast the Gate")
	var result: Dictionary = keep.advance_wave(6.0)
	_expect(bool(result.get("resolved", false)), "six seconds should resolve the basic wave")
	_expect(String(result.get("outcome", "")) == "held", "Pike Line should hold the basic Raider wave")
	_expect(keep.room_condition("gate") > 0, "a successful Pike Line should absorb limited contact without losing the Gate")
	_expect(keep.materials > 43, "holding a wave should award recovery materials")

func _test_sapper_targeting_and_repair() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	keep.place_piece("pike_squad", Vector2i(0, 3), "ground")
	keep.open_pack("field_engineers")
	keep.open_pack("scouts")
	keep.place_piece("repair_station", Vector2i(4, 6), "ground")
	keep.place_piece("scout_post", Vector2i(8, 1), "upper")
	var started: Dictionary = keep.start_wave("distributed_sabotage")
	_expect(bool(started.get("ok", false)), "distributed sabotage should start")
	var result: Dictionary = keep.advance_wave(6.0)
	_expect(bool(result.get("resolved", false)), "distributed sabotage should resolve in the slice")
	_expect(keep.room_condition("workshop") < 100 or keep.room_condition("supply_room") < 100 or keep.room_condition("armory") < 100, "Sapper should damage a support target")
	_expect(String(result.get("timeline", []).filter(func(line: String) -> bool: return line.contains("Sapper reached")).front()).contains("Sapper reached"), "battle report should explain Sapper targeting")
	var repaired: Dictionary = keep.repair_room("workshop")
	_expect(bool(repaired.get("ok", false)) or keep.room_condition("workshop") == 100, "a damaged support room should have a repair path")

func _test_climber_targets_upper_floor() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	keep.open_pack("scouts")
	keep.place_piece("scout_post", Vector2i(8, 1), "upper")
	var started: Dictionary = keep.start_wave("feint_and_flank")
	_expect(bool(started.get("ok", false)), "feint and flank should start")
	var result: Dictionary = keep.advance_wave(6.0)
	_expect(bool(result.get("resolved", false)), "climber wave should resolve")
	_expect(keep.room_condition("north_tower") < 100 or keep.room_condition("old_chapel") < 100, "Climber should target an upper-floor room")

func _test_lockdown_changes_room_damage() -> void:
	var normal: PackKeepState = PackKeepState.new(3307)
	var locked: PackKeepState = PackKeepState.new(3307)
	normal.open_pack("scouts")
	locked.open_pack("scouts")
	normal.place_piece("scout_post", Vector2i(0, 0), "upper")
	locked.place_piece("scout_post", Vector2i(0, 0), "upper")
	normal.start_wave("gate_assault")
	locked.start_wave("gate_assault")
	locked.use_commander_ability()
	normal.advance_wave(2.0)
	locked.advance_wave(2.0)
	_expect(locked.room_condition("gate") > normal.room_condition("gate"), "Lockdown should reduce the next contact damage")
	_expect(locked.command_points == 2, "Lockdown should consume one command point")
	_expect(not bool(locked.use_commander_ability().get("ok", false)), "Lockdown should be limited to once per wave")

func _test_partial_breach_is_recoverable() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	keep.open_pack("scouts")
	keep.place_piece("scout_post", Vector2i(0, 0), "upper")
	keep.start_wave("gate_assault")
	var result: Dictionary = keep.advance_wave(6.0)
	_expect(String(result.get("outcome", "")) == "partial_breach", "an unsupported Gate should create a partial breach rather than a silent win")
	_expect(not keep.wave_active, "a resolved partial breach should leave the wave inactive")
	_expect(keep.room_state("gate") == "breached", "the report should identify the breached Gate")
	var repair: Dictionary = keep.repair_room("gate")
	_expect(bool(repair.get("ok", false)), "a partial breach should expose a repair path")

func _test_repair_interval_and_assignments() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	keep.select_scenario("gatehouse_lock")
	keep.open_pack("scouts")
	keep.place_piece("scout_post", Vector2i(8, 1), "upper")
	keep.start_wave("gate_assault")
	var result: Dictionary = keep.advance_wave(6.0)
	_expect(String(result.get("outcome", "")) == "partial_breach", "unsupported Gate should open a recoverable interval")
	_expect(keep.repair_interval_active, "held or partial-breach outcomes should open the repair interval")
	_expect(keep.repair_actions_remaining == 2, "Greywatch interval should begin with two actions")
	var repaired: Dictionary = keep.repair_room("gate")
	_expect(bool(repaired.get("ok", false)), "the first interval action should repair a named room")
	_expect(keep.room_condition("gate") == 30, "repair should restore a breached room to 30 condition")
	var assignment: Dictionary = keep.assign_piece_to_room("scout_post_0", "north_tower")
	_expect(bool(assignment.get("ok", false)), "the second interval action should assign Scout Post to North Tower")
	_expect(keep.assigned_rooms.get("north_tower", "") == "scout_post_0", "assignment should be stored by room")
	_expect(keep.pieces["scout_post_0"].get("assignment", "") == "north_tower", "assignment should be stored on the piece")
	_expect(keep.repair_actions_remaining == 0, "two repair interval actions should be consumed")
	_expect(not bool(keep.start_wave("gate_assault").get("ok", false)), "the next wave should wait for interval closure")
	var finished: Dictionary = keep.finish_repair_interval()
	_expect(bool(finished.get("ok", false)), "the repair interval should close explicitly")
	_expect(not keep.repair_interval_active, "closed interval should no longer block a wave")
	_expect(bool(finished.get("next_wave_started", false)), "closing an authored interval should start the next wave automatically")
	_expect(keep.wave_active and keep.wave_index == 2, "automatic recovery should leave wave two active")

func _test_assignment_rules_and_action_budget() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	keep.place_piece("pike_squad", Vector2i(0, 3), "ground")
	keep.open_pack("field_engineers")
	keep.place_piece("repair_station", Vector2i(4, 6), "ground")
	keep.start_wave("gate_assault")
	keep.advance_wave(6.0)
	var pike_assignment: Dictionary = keep.assign_piece_to_room("pike_squad_0", "workshop")
	_expect(not bool(pike_assignment.get("ok", false)), "Pike Squad should reject an invalid room-role assignment")
	var valid_pike: Dictionary = keep.assign_piece_to_room("pike_squad_0", "gate")
	_expect(bool(valid_pike.get("ok", false)), "Pike Squad should assign to the Gate")
	var valid_repair: Dictionary = keep.assign_piece_to_room("repair_station_1", "workshop")
	_expect(bool(valid_repair.get("ok", false)), "Repair Station should assign to the Workshop")
	_expect(not bool(keep.assign_piece_to_room("pike_squad_0", "gate").get("ok", false)), "an already assigned piece should not be assigned twice")
	_expect(not bool(keep.repair_room("gate").get("ok", false)), "no third interval action should be available")
	_expect(bool(keep.finish_repair_interval().get("ok", false)), "interval should close after assignment actions")

func _test_recovery_action_previews() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	keep.place_piece("pike_squad", Vector2i(3, 3), "ground")
	var closed_preview: Dictionary = keep.recovery_action_preview("assign_piece", "pike_squad_0", "gate")
	_expect(not bool(closed_preview.get("ok", false)) and String(closed_preview.get("reason", "")).contains("no recovery interval"), "recovery previews should reject actions outside recovery")
	keep.rooms["gate"].condition = 40
	keep._update_room_state("gate")
	keep._set_piece_health("pike_squad_0", 7)
	keep.repair_interval_active = true
	keep.repair_actions_remaining = 2
	var serialized_before: String = JSON.stringify(keep.serialize())
	var room_preview: Dictionary = keep.recovery_action_preview("repair_room", "", "gate")
	var piece_preview: Dictionary = keep.recovery_action_preview("repair_piece", "pike_squad_0")
	var assignment_preview: Dictionary = keep.recovery_action_preview("assign_piece", "pike_squad_0", "gate")
	var invalid_assignment: Dictionary = keep.recovery_action_preview("assign_piece", "pike_squad_0", "workshop")
	var clear_preview: Dictionary = keep.recovery_action_preview("clear_assignment", "pike_squad_0")
	_expect(bool(room_preview.get("ok", false)) and int(room_preview.get("material_cost", 0)) == 8, "room preview should expose legal cost before mutation")
	_expect(bool(piece_preview.get("ok", false)) and int(piece_preview.get("material_cost", 0)) == 6, "piece preview should expose legal cost before mutation")
	_expect(bool(assignment_preview.get("ok", false)), "assignment preview should accept a legal adjacent specialist target")
	_expect(not bool(invalid_assignment.get("ok", false)) and String(invalid_assignment.get("reason", "")).contains("Gate"), "assignment preview should explain the specialist room restriction")
	_expect(not bool(clear_preview.get("ok", false)) and String(clear_preview.get("reason", "")).contains("no room assignment"), "clear preview should explain when no assignment exists")
	_expect(JSON.stringify(keep.serialize()) == serialized_before, "recovery previews must not mutate serialized state")
	var repaired: Dictionary = keep.repair_room("gate")
	_expect(bool(repaired.get("ok", false)) and not repaired.get("state_changes", []).is_empty(), "room repair should report structured state changes")
	var assigned: Dictionary = keep.assign_piece_to_room("pike_squad_0", "gate")
	_expect(bool(assigned.get("ok", false)) and not assigned.get("state_changes", []).is_empty(), "assignment should report structured state changes")
	var exhausted: Dictionary = keep.recovery_action_preview("repair_piece", "pike_squad_0")
	_expect(not bool(exhausted.get("ok", false)) and String(exhausted.get("reason", "")).contains("no recovery actions"), "preview should expose an exhausted action budget")

func _test_causal_scenario_reports() -> void:
	var held: PackKeepState = PackKeepState.new(3307)
	held.place_piece("pike_squad", Vector2i(0, 3), "ground")
	held.start_wave("gate_assault")
	held.advance_wave(6.0)
	var held_before: String = JSON.stringify(held.serialize())
	var held_report: Dictionary = held.scenario_report()
	_expect(JSON.stringify(held.serialize()) == held_before, "scenario report must not mutate authoritative state")
	_expect(String(held_report.get("commander_name", "")).contains("Castellan"), "scenario report should identify the commander")
	_expect(not held_report.get("wave_rows", []).is_empty() and String(held_report.wave_rows[0].get("principal_pressure", "")).contains("Gate"), "scenario report should name the wave's principal pressure")
	_expect(String(held_report.get("what_worked", [""])[0]).contains("held"), "held report should derive a concrete success")

	var partial: PackKeepState = PackKeepState.new(3307)
	partial.open_pack("scouts")
	partial.place_piece("scout_post", Vector2i(0, 0), "upper")
	partial.start_wave("gate_assault")
	partial.advance_wave(6.0)
	var partial_report: Dictionary = partial.scenario_report()
	_expect(partial.last_outcome == "partial_breach", "partial-report fixture should produce a partial breach")
	_expect(String(partial_report.get("what_failed", [""])[0]).contains("breached"), "partial-breach report should identify breached waves")
	_expect(String(partial_report.get("suggested_experiment", "")).contains("Pike Squad"), "Gate damage should suggest a concrete Gate experiment")

	var collapsed: PackKeepState = PackKeepState.new(3307)
	collapsed.open_pack("scouts")
	collapsed.place_piece("scout_post", Vector2i(0, 0), "upper")
	collapsed.start_wave("gate_assault")
	collapsed.morale = 0
	collapsed.advance_wave(6.0)
	var collapsed_report: Dictionary = collapsed.scenario_report()
	_expect(collapsed.last_outcome == "collapse", "collapse-report fixture should produce collapse")
	_expect(String(collapsed_report.get("what_failed", [""])[0]).contains("collapsed"), "collapse report should identify the terminal failure threshold")
	_expect(String(collapsed_report.get("suggested_experiment", "")).contains("same seed"), "collapse report should preserve a deterministic replay experiment")

func _test_layout_summary_and_commander_comparison() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	var empty_before: String = JSON.stringify(keep.serialize())
	var empty_summary: Dictionary = keep.layout_summary()
	_expect(JSON.stringify(keep.serialize()) == empty_before, "layout comparison must not mutate authoritative state")
	_expect(empty_summary.get("commander_comparison", {}).has("castellan") and empty_summary.get("commander_comparison", {}).has("warden"), "layout summary should compare both commanders")
	_expect(String(" | ".join(empty_summary.get("duplicate_role_warnings", []))).contains("No ground-floor"), "empty layout should expose missing ground coverage")
	keep.place_piece("pike_squad", Vector2i(3, 3), "ground")
	keep.place_piece("pike_squad", Vector2i(5, 3), "ground")
	keep.open_pack("scouts")
	keep.place_piece("scout_post", Vector2i(8, 1), "upper")
	var summary_before: String = JSON.stringify(keep.serialize())
	var summary: Dictionary = keep.layout_summary()
	_expect(JSON.stringify(keep.serialize()) == summary_before, "populated layout comparison must remain read-only")
	_expect(int(summary.get("counts", {}).get("ground", 0)) == 2 and int(summary.get("counts", {}).get("upper", 0)) == 1, "layout summary should count both floors")
	_expect(int(summary.get("open_lane_count", 0)) == 3, "layout summary should count open response cells independent of commander")
	_expect(int(summary.get("support_piece_count", 0)) == 1 and int(summary.get("signal_piece_count", 0)) == 1, "layout summary should expose support and signal coverage")
	_expect(String(" | ".join(summary.get("duplicate_role_warnings", []))).contains("2 melee"), "layout summary should warn about duplicate combat roles")

func _test_deterministic_battle_report() -> void:
	var first: PackKeepState = PackKeepState.new(17)
	var second: PackKeepState = PackKeepState.new(17)
	for keep in [first, second]:
		keep.place_piece("pike_squad", Vector2i(0, 3), "ground")
		keep.open_pack("field_engineers")
		keep.open_pack("scouts")
		keep.place_piece("repair_station", Vector2i(4, 6), "ground")
		keep.place_piece("scout_post", Vector2i(8, 1), "upper")
		keep.start_wave("distributed_sabotage")
	first.advance_wave(6.0)
	second.advance_wave(6.0)
	_expect(first.last_outcome == second.last_outcome, "same seed and layout should produce the same outcome")
	_expect(first.rooms == second.rooms, "same seed and layout should produce the same room state")
	_expect(first.battle_report == second.battle_report, "same seed and layout should produce the same causal report")

func _test_p0_pack_preview_and_reserve() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	var preview: Dictionary = keep.pack_preview("field_engineers")
	_expect(bool(preview.get("ok", false)), "P0 should preview a known pack")
	_expect(int(preview.get("cost", 0)) == 4, "pack preview should expose the pack cost")
	_expect(preview.get("pieces", []).size() == 2, "pack preview should list both contained pieces")
	_expect(String(preview.get("solves", "")).contains("Room damage"), "pack preview should explain its problem-solving role")
	var reserved: Dictionary = keep.reserve_pack("field_engineers")
	_expect(bool(reserved.get("ok", false)), "P0 should reserve an unowned pack")
	_expect(keep.reserved_pack_id == "field_engineers", "reserve should be stored without granting pieces")
	_expect(not keep.available_pieces.has("repair_station"), "reserved pack pieces should remain unavailable")
	var opened: Dictionary = keep.open_pack("field_engineers")
	_expect(bool(opened.get("ok", false)), "a reserved pack should still be openable")
	_expect(keep.materials == 56, "opening a pack should consume its previewed materials cost")
	_expect(keep.reserved_pack_id.is_empty(), "opening the reserved pack should clear the reserve slot")
	_expect(not bool(keep.open_pack("field_engineers").get("ok", false)), "an owned pack should not open twice")

func _test_p0_placement_preview_and_inspection() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	var unavailable: Dictionary = keep.piece_preview("repair_station", Vector2i(4, 6), "ground")
	_expect(not bool(unavailable.get("valid", false)), "P0 preview should reject an unavailable piece")
	var valid: Dictionary = keep.piece_preview("pike_squad", Vector2i(0, 3), "ground")
	_expect(bool(valid.get("valid", false)), "P0 preview should accept an affordable open footprint")
	_expect(int(valid.get("remaining_materials", -1)) == 52, "placement preview should show remaining materials")
	keep.place_piece("pike_squad", Vector2i(0, 3), "ground")
	var overlap: Dictionary = keep.piece_preview("narrow_gate", Vector2i(0, 3), "ground")
	_expect(not bool(overlap.get("valid", false)), "P0 preview should reject an overlapping footprint")
	var piece_inspection: Dictionary = keep.inspect_piece("pike_squad_0")
	_expect(bool(piece_inspection.get("ok", false)), "P0 should inspect a placed piece")
	_expect(String(piece_inspection.get("role", "")).contains("Gate"), "piece inspection should explain the unit role")
	var room_inspection: Dictionary = keep.inspect_room("gate")
	_expect(bool(room_inspection.get("ok", false)), "P0 should inspect a keep room")
	_expect(bool(room_inspection.get("critical", false)), "room inspection should expose criticality")
	keep.start_wave("gate_assault")
	var enemy_inspection: Dictionary = keep.inspect_enemy(0)
	_expect(bool(enemy_inspection.get("ok", false)), "P0 should inspect an active enemy")
	_expect(String(enemy_inspection.get("doctrine", "")).contains("gate"), "enemy inspection should explain its doctrine")

func _test_p0_save_rejection_and_reset() -> void:
	var keep: PackKeepState = PackKeepState.new(19)
	keep.reserve_pack("scouts")
	keep.place_piece("pike_squad", Vector2i(0, 3), "ground")
	var serialized: Dictionary = keep.serialize()
	_expect(int(serialized.get("schema_version", 0)) == PackKeepState.SAVE_SCHEMA_VERSION, "P0 saves should carry the current schema version")
	_expect(String(serialized.get("game_id", "")) == PackKeepState.GAME_ID, "P0 saves should carry the game ID")
	var future: Dictionary = serialized.duplicate(true)
	future["schema_version"] = PackKeepState.SAVE_SCHEMA_VERSION + 1
	var restored: PackKeepState = PackKeepState.new(0)
	var rejected: Dictionary = restored.load_serialized(future)
	_expect(not bool(rejected.get("ok", false)), "future-version saves should be rejected")
	_expect(restored.seed == 0 and restored.pieces.is_empty(), "rejecting a future save should leave the current state intact")
	var malformed: Dictionary = serialized.duplicate(true)
	malformed["pieces"] = ["not", "a", "dictionary"]
	var malformed_result: Dictionary = restored.load_serialized(malformed)
	_expect(not bool(malformed_result.get("ok", false)), "malformed piece collections should be rejected")
	var state_before_nested_rejections: String = JSON.stringify(restored.serialize())
	var malformed_piece_entry: Dictionary = serialized.duplicate(true)
	malformed_piece_entry.pieces = {"broken": "not an object"}
	_expect(not bool(restored.load_serialized(malformed_piece_entry).get("ok", false)), "non-object piece entries should be rejected")
	_expect(JSON.stringify(restored.serialize()) == state_before_nested_rejections, "rejecting a nested piece entry should not partially mutate state")
	var unknown_piece: Dictionary = serialized.duplicate(true)
	unknown_piece.pieces["pike_squad_0"].piece_id = "unknown_piece"
	_expect(not bool(restored.load_serialized(unknown_piece).get("ok", false)), "unknown saved piece IDs should be rejected")
	_expect(JSON.stringify(restored.serialize()) == state_before_nested_rejections, "rejecting an unknown piece should not partially mutate state")
	var malformed_enemy_entry: Dictionary = serialized.duplicate(true)
	malformed_enemy_entry.enemies = ["not an object"]
	_expect(not bool(restored.load_serialized(malformed_enemy_entry).get("ok", false)), "non-object enemy entries should be rejected")
	_expect(JSON.stringify(restored.serialize()) == state_before_nested_rejections, "rejecting a nested enemy entry should not partially mutate state")
	var incomplete_rooms: Dictionary = serialized.duplicate(true)
	incomplete_rooms.rooms.erase("gate")
	_expect(not bool(restored.load_serialized(incomplete_rooms).get("ok", false)), "incomplete saved room maps should be rejected")
	_expect(JSON.stringify(restored.serialize()) == state_before_nested_rejections, "rejecting incomplete rooms should not partially mutate state")
	var broken_assignment: Dictionary = serialized.duplicate(true)
	broken_assignment.assigned_rooms = {"gate": "missing_piece"}
	_expect(not bool(restored.load_serialized(broken_assignment).get("ok", false)), "assignments to missing pieces should be rejected")
	_expect(JSON.stringify(restored.serialize()) == state_before_nested_rejections, "rejecting a broken assignment should not partially mutate state")
	var unknown_commander: Dictionary = serialized.duplicate(true)
	unknown_commander.seed = 1234
	unknown_commander.commander_id = "unknown_commander"
	_expect(not bool(restored.load_serialized(unknown_commander).get("ok", false)), "unknown saved commanders should be rejected")
	_expect(JSON.stringify(restored.serialize()) == state_before_nested_rejections, "identity validation should happen before any saved field mutates state")
	keep.reset_run(77)
	_expect(keep.seed == 77 and keep.pieces.is_empty(), "reset should clear placed pieces")
	_expect(keep.reserved_pack_id.is_empty() and keep.available_pieces == ["pike_squad", "narrow_gate"], "reset should clear reserve and restore starter availability")

func _test_p1_warden_and_rally() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	var selected: Dictionary = keep.select_commander("warden")
	_expect(bool(selected.get("ok", false)), "Warden should be selectable")
	_expect(keep.materials == 52 and keep.morale == 7, "Warden should start with lower materials and higher morale")
	_expect(String(keep.commander_definition("warden").get("ability", "")) == "rally", "Warden should expose Rally as its active ability")
	keep.open_pack("firekeepers")
	keep.place_piece("fire_team", Vector2i(4, 3), "ground")
	keep.start_wave("area_pressure")
	var rallied: Dictionary = keep.use_commander_ability()
	_expect(bool(rallied.get("ok", false)), "Warden Rally should arm during an active wave")
	_expect(keep.morale == 8 and keep.command_points == 2, "Rally should restore morale and consume one command point")
	_expect(not bool(keep.use_commander_ability().get("ok", false)), "Rally should be limited to once per wave")
	keep.advance_wave(1.0)
	_expect(not keep.rally_pending, "Rally should release after its coordinated response step")

func _test_p1_siege_beast_area_pressure() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	keep.open_pack("firekeepers")
	keep.place_piece("fire_team", Vector2i(4, 3), "ground")
	var started: Dictionary = keep.start_wave("area_pressure")
	_expect(bool(started.get("ok", false)), "area pressure should start as a P1 doctrine")
	_expect(str(started.get("composition", []).front()) == "siege_beast", "area pressure should contain a Siege Beast")
	var enemy: Dictionary = keep.inspect_enemy(0)
	_expect(bool(enemy.get("ok", false)) and String(enemy.get("name", "")) == "Siege Beast", "Siege Beast should be inspectable")
	keep.advance_wave(3.0)
	_expect(keep.room_condition("inner_yard") < 100 or keep.room_condition("outer_wall") < 100, "Siege Beast should damage an area rather than one isolated target")
	_expect(int(keep.combat_metrics.get("room_damage", 0)) > 15, "Siege Beast area impact should aggregate multiple room damage")

func _test_p1_scenario_escalation() -> void:
	var keep: PackKeepState = PackKeepState.new(3307)
	var selected: Dictionary = keep.select_scenario("gatehouse_lock")
	_expect(bool(selected.get("ok", false)), "Gatehouse Lock scenario should be selectable on a new run")
	keep.place_piece("pike_squad", Vector2i(0, 3), "ground")
	var first: Dictionary = keep.start_wave("gate_assault")
	_expect(bool(first.get("ok", false)) and keep.enemy_doctrine == "gate_assault", "scenario wave one should preserve its teaching doctrine")
	keep.advance_wave(6.0)
	var finished_one: Dictionary = keep.finish_repair_interval()
	_expect(bool(finished_one.get("next_wave_started", false)), "finishing wave one recovery should auto-start wave two")
	var second: Dictionary = {"ok": keep.wave_active, "composition": keep.enemies.map(func(enemy: Dictionary) -> String: return String(enemy.get("enemy_id", "")))}
	_expect(bool(second.get("ok", false)) and keep.enemy_doctrine == "distributed_sabotage", "scenario wave two should escalate to a different doctrine")
	_expect(second.get("composition", []).has("sapper"), "scenario wave two should introduce a Sapper")
	keep.advance_wave(6.0)
	var finished_two: Dictionary = keep.finish_repair_interval()
	_expect(bool(finished_two.get("next_wave_started", false)), "finishing wave two recovery should auto-start wave three")
	_expect(keep.wave_active and keep.wave_index == 3 and keep.enemy_doctrine == "feint_and_flank", "scenario wave three should remain available and escalate")
	keep.advance_wave(6.0)
	var finished_three: Dictionary = keep.finish_repair_interval()
	_expect(bool(finished_three.get("ok", false)) and not bool(finished_three.get("next_wave_started", false)), "final wave recovery should close without starting a fourth wave")
	_expect(not bool(keep.start_wave("gate_assault").get("ok", false)), "authored scenario should stop after three waves")

func _test_p1_seeded_variation() -> void:
	var first: PackKeepState = PackKeepState.new(3307)
	var second: PackKeepState = PackKeepState.new(3307)
	var alternate: PackKeepState = PackKeepState.new(3308)
	first.select_scenario("open_yard_net")
	second.select_scenario("open_yard_net")
	alternate.select_scenario("open_yard_net")
	_expect(first.scenario_variation_id == second.scenario_variation_id, "same seed and scenario should choose the same variation")
	_expect(first.variation_target_room == second.variation_target_room and first.variation_materials == second.variation_materials, "same seed should preserve the same variation values")
	_expect(first.scenario_variation_id != alternate.scenario_variation_id or first.variation_target_room != alternate.variation_target_room or first.variation_materials != alternate.variation_materials, "a neighboring seed should be able to produce bounded variation")
	var preview: Dictionary = first.scenario_preview()
	_expect(int(preview.get("wave_count", 0)) == 3 and String(preview.get("objective", "")).contains("Old Chapel"), "scenario preview should expose its objective and wave count")

func _test_save_round_trip() -> void:
	var keep: PackKeepState = PackKeepState.new(17)
	keep.place_piece("pike_squad", Vector2i(0, 3), "ground")
	keep.open_pack("scouts")
	keep.place_piece("scout_post", Vector2i(8, 1), "upper")
	keep.start_wave("feint_and_flank")
	keep.advance_wave(1.0)
	var restored: PackKeepState = PackKeepState.new(0)
	restored.load_serialized(keep.serialize())
	_expect(restored.seed == 17, "save should preserve seed")
	_expect(restored.commander_id == "castellan", "save should preserve commander")
	_expect(restored.pieces.size() == 2, "save should preserve pieces")
	_expect(restored.available_pieces == keep.available_pieces, "save should preserve unlocked unit availability")
	_expect(restored.pieces["pike_squad_0"].health == keep.pieces["pike_squad_0"].health, "save should preserve unit health")
	_expect(restored.combat_metrics == keep.combat_metrics, "save should preserve combat metrics")
	_expect(restored.rooms == keep.rooms, "save should preserve room condition")
	_expect(restored.enemies == keep.enemies, "save should preserve active enemies")
	_expect(restored.wave_active == keep.wave_active, "save should preserve wave state")
	var disk_source: PackKeepState = PackKeepState.new(24)
	disk_source.open_pack("field_engineers")
	disk_source.place_piece("repair_station", Vector2i(4, 3), "ground")
	var disk_payload: Variant = JSON.parse_string(JSON.stringify(disk_source.serialize()))
	var disk_restored: PackKeepState = PackKeepState.new(0)
	var disk_result: Dictionary = disk_restored.load_serialized(disk_payload)
	_expect(bool(disk_result.get("ok", false)), "JSON-decoded saves should pass nested validation")
	_expect(disk_restored.pieces["repair_station_0"].origin == Vector2i(4, 3), "JSON-decoded piece origins should survive validation and decoding")
